name: Deploy Todos tus libros Docker
on:
  push:
    tags:
          - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set lowercase repo
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Inyectar variables de entorno
        working-directory: ./frontend
        run: |
          echo "VITE_ULTRA_TOKEN=${{ secrets.VITE_ULTRA_TOKEN }}" >> .env
          sed -i '/\.env/d' .dockerignore || true

      - name: Build image
        working-directory: ./frontend
        run: |
          docker build -t ghcr.io/$REPO:latest .

      - name: Push image
        run: |
          docker push ghcr.io/$REPO:latest